services:
  pinyator:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_DATABASE
    restart: unless-stopped
    ports:
      - 14242:80
      - 3306:3306
    volumes:
      - "pinyator-db:/db"
      - "./pinyator:/var/www/html/pinyator"
    env_file:
      - .env

volumes:
  pinyator-db:
